version: '2.4'

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:plexpass
    restart: always
    volumes:
      - config:/config
      - transcode:/transcode
      - /mnt/media/plex:/data
      - /mnt/media/transmission/racing/downloads:/racing
    ports:
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - ADVERTISE_IP=http://192.168.1.20:32400/

volumes:
  config:
  transcode:
